const BUGS=[
{title:"The Vanishing Total",question:"A student enters two marks, but the total is always wrong. Find the bug.",code:`int a = 40;\nint b = 35;\nint total;\n\ntotal = a - b;\ncout << total;`,answers:["minus","subtraction","a - b"],hint:"Look at the operator used to calculate the total.",explanation:"The total uses subtraction. Marks should be added: total = a + b;"},
{title:"The Sneaky Loop",question:"This loop is supposed to print 1 to 5. What is wrong?",code:`for(int i = 1; i < 5; i++) {\n    cout << i << " ";\n}`,answers:["<=","less than","5"],hint:"Will the loop ever print 5?",explanation:"The condition i < 5 stops before 5. Use i <= 5."},
{title:"The Mystery Variable",question:"The program refuses to compile. Find the problem.",code:`int marks = 80;\ncout << mark;`,answers:["marks","variable","spelling"],hint:"Compare the variable declaration with the variable being printed.",explanation:"The declared variable is marks, but the program uses mark."},
{title:"The Divide Disaster",question:"The average should allow decimal values. What should you consider?",code:`int total = 155;\nint subjects = 2;\nint average;\n\naverage = total / subjects;`,answers:["integer","float","double","decimal"],hint:"What happens when two integers are divided?",explanation:"Use float or double when an average may need decimal precision."},
{title:"The Infinite Trouble",question:"The program gets stuck. Identify the debugging clue.",code:`int i = 1;\nwhile(i <= 5) {\n    cout << i;\n}`,answers:["increment","i++","infinite","loop"],hint:"What changes the value of i?",explanation:"i never changes, so the condition remains true. Add i++ inside the loop."}
];
let s={reg:"",i:0,score:0,start:"",answers:[]};const $=x=>document.getElementById(x);const hide=x=>$(x).classList.add("hidden"),show=x=>$(x).classList.remove("hidden");
function nav(){let n=$("qnav");n.innerHTML="";BUGS.forEach((b,i)=>{let x=document.createElement("button");x.className="qbtn"+(i===s.i?" current":"")+(s.answers[i].submitted?" done":"");x.textContent=i+1;x.type="button";x.onclick=()=>go(i);n.appendChild(x)})}
function render(){let b=BUGS[s.i],a=s.answers[s.i];$("title").textContent=b.title;$("question").textContent=b.question;$("code").textContent=b.code;$("answer").value=a.text||"";$("score").textContent=s.score;$("counter").textContent=`Challenge ${s.i+1} of ${BUGS.length}`;$("bar").style.width=((s.i+1)/BUGS.length*100)+"%";$("answered").textContent=s.answers.filter(x=>x.submitted).length;$("total").textContent=BUGS.length;$("prev").disabled=s.i===0;$("next").textContent=s.i===BUGS.length-1?"Last Bug →":"Next Bug →";$("feedback").innerHTML="";if(a.submitted){$("answer").disabled=true;$("check").disabled=true;$("hint").disabled=true;$("feedback").innerHTML=`<div class="feedback ${a.correct?'good':'bad'}">${a.correct?'🎉 Correct!':'🕵️ Not quite.'} ${b.explanation}</div>`}else{$("answer").disabled=false;$("check").disabled=false;$("hint").disabled=false}nav()}
function go(i){if(i<0||i>=BUGS.length)return;s.i=i;render();scrollTo({top:0,behavior:"smooth"})}
function start(){let r=$("reg").value.trim().toUpperCase().replace(/\s+/g,"");if(!/^[A-Z0-9-]{4,20}$/.test(r)){$("loginMsg").textContent="Please enter a valid register number.";return}s={reg:r,i:0,score:0,start:new Date().toISOString(),answers:BUGS.map(()=>({submitted:false,correct:false,text:""}))};$("student").textContent="👨‍💻 "+r;hide("login");show("game");render()}
function check(){let a=s.answers[s.i],text=$("answer").value.trim().toLowerCase();if(a.submitted)return;if(!text){$("feedback").innerHTML='<div class="feedback hint">✏️ Write what you think the bug is first.</div>';return}let b=BUGS[s.i],ok=b.answers.some(x=>text.includes(x));a.submitted=true;a.correct=ok;a.text=$("answer").value;if(ok)s.score++;$("score").textContent=s.score;$("feedback").innerHTML=`<div class="feedback ${ok?'good':'bad'}">${ok?'🎉 Nice catch!':'🕵️ Not quite.'} ${b.explanation}</div>`;$("answer").disabled=$("check").disabled=$("hint").disabled=true;nav();$("answered").textContent=s.answers.filter(x=>x.submitted).length}
async function finish(){let left=s.answers.filter(x=>!x.submitted).length;if(left&&!confirm(`You still have ${left} unanswered question(s). Finish anyway?`))return;await save({register_number:s.reg,score:s.score,max_score:BUGS.length,percentage:Math.round(s.score/BUGS.length*100),attempt:1,started_at:s.start,completed_at:new Date().toISOString()});hide("game");show("done");$("finalScore").textContent=s.score;$("finalMax").textContent=BUGS.length;$("finalMsg").textContent=s.score>=4?"Excellent debugging instincts! 🧠":s.score>=3?"Good work — keep hunting those bugs! 🔎":"Every bug you found was practice. Debug again and beat your score! 🐞"}
async function save(row){if(window.sb){let{error}=await window.sb.from("bug_buster_results").insert(row);if(error)console.error(error)}else{let a=JSON.parse(localStorage.getItem("bugBusterResults")||"[]");a.push(row);localStorage.setItem("bugBusterResults",JSON.stringify(a))}}
async function init(){if(CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_ANON_KEY)try{let m=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");window.sb=m.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY)}catch(e){console.error(e)}}
$("start").onclick=start;$("check").onclick=check;$("hint").onclick=()=>$("feedback").innerHTML=`<div class="feedback hint">💡 ${BUGS[s.i].hint}</div>`;$("prev").onclick=()=>go(s.i-1);$("next").onclick=()=>go(s.i===BUGS.length-1?0:s.i+1);$("finish").onclick=finish;$("again").onclick=start;$("reg").onkeydown=e=>{if(e.key==="Enter")start()};init();
