let rows=[];const $=x=>document.getElementById(x);
async function init(){if(CONFIG.SUPABASE_URL&&CONFIG.SUPABASE_ANON_KEY)try{let m=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");window.sb=m.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY)}catch(e){console.error(e)}}
async function get(){if(window.sb){let{data,error}=await window.sb.from("bug_buster_results").select("*").order("completed_at",{ascending:false});if(error)throw error;return data||[]}return JSON.parse(localStorage.getItem("bugBusterResults")||"[]")}
function render(){let q=$("search").value.trim().toUpperCase(),r=rows.filter(x=>(x.register_number||"").toUpperCase().includes(q));$("body").innerHTML=r.map(x=>`<tr><td>${esc(x.register_number)}</td><td>${x.score}</td><td>${x.max_score}</td><td>${x.percentage}%</td><td>${x.attempt}</td><td>${x.completed_at?new Date(x.completed_at).toLocaleString():""}</td></tr>`).join("");$("students").textContent=new Set(rows.map(x=>x.register_number)).size;$("attempts").textContent=rows.length;$("average").textContent=rows.length?Math.round(rows.reduce((a,x)=>a+Number(x.percentage||0),0)/rows.length)+"%":"0%"}
function esc(v){return String(v??"").replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
async function refresh(){ $("status").textContent="Loading...";try{rows=await get();render();$("status").textContent=window.sb?`${rows.length} result(s) loaded from Supabase.`:"Demo mode: results are stored only in this browser."}catch(e){console.error(e);$("status").textContent="Could not load results. Check Supabase configuration and policies."}}
function csv(){let h=["Register Number","Score","Max Score","Percentage","Attempt","Completed"],lines=[h.join(",")];rows.forEach(x=>lines.push([x.register_number,x.score,x.max_score,x.percentage,x.attempt,x.completed_at?new Date(x.completed_at).toLocaleString():""].map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")));let u=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download="bug-buster-marks.csv";a.click();URL.revokeObjectURL(u)}
$("loginBtn").onclick=()=>{if($("password").value!==CONFIG.TEACHER_ACCESS_CODE){$("loginMsg").textContent="Incorrect access code.";return}hide("login");show("dash");refresh()};$("refresh").onclick=refresh;$("download").onclick=csv;$("search").oninput=render;init();
function hide(x){$(x).classList.add("hidden")}function show(x){$(x).classList.remove("hidden")}
